[package]
name = "autoreport-bwrap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "bwrap"
path = "src/main.rs"

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true

[build-dependencies]
cc = "1"
pkg-config = "0.3"
