mod approval_overlay;
mod chat_composer;
mod completion_popup;
pub(crate) mod history_search;
pub(crate) mod paste_burst;
mod pending_input_preview;
mod popup_state;
mod rendering;
mod request_user_input_overlay;
mod status_indicator_widget;
pub(crate) mod status_line_style;

pub(crate) use approval_overlay::ApprovalOverlay;
pub(crate) use chat_composer::ChatComposer;
pub(crate) use completion_popup::CompletionPopup;
pub(crate) use pending_input_preview::PendingInputPreview;
pub(crate) use rendering::BottomPane;
pub(crate) use request_user_input_overlay::RequestUserInputOverlay;
pub(crate) use status_indicator_widget::{StatusIndicatorWidget, fmt_elapsed_compact};
pub(crate) mod status_line_setup;
