[package]
name = "autoreport-async-utils"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "time"] }
tokio-util.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true

[lib]
name = "autoreport_async_utils"
path = "src/lib.rs"
doctest = false
